kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: package
    image: debian:9
    commands:
      - apt-get -qq update
      - apt-get install -y -qq openssh-client
      - ssh -vvv repo.lib.helsinki.fi


