---
index:
  analysis:
    analyzer:
      analyser_phrase:
        tokenizer: keyword
        filter:
          - finnish_folding
          - lowercase
        char_filter:
          punctuation
      analyser_standard:
        tokenizer: icu_tokenizer
        filter:
          - finnish_folding
          - lowercase
        char_filter: punctuation
      analyser_stdno:
        tokenizer: whitespace
        filter: 
          - finnish_folding
          - lowercase
        char_filter:
          punctuation
    normalizer:
      normalizer_keyword:
        type: custom
        filter: 
          - finnish_folding
          - lowercase
    filter:
      finnish_folding:
        type: icu_folding
        unicodeSetFilter: '[^åäöÅÄÖ]'
    char_filter:
      punctuation:
        type: mapping
        mappings:
          - '- => '
          - '+ => '
          - ', => '
          - '. => '
          - '= => '
          - '; => '
          - ': => '
          - '" => '
          - ''' => '
          - '! => '
          - '? => '
          - '% => '
          - '\/ => '
          - '( => '
          - ') => '
          - '[ => '
          - '] => '
          - '{ => '
          - '} => '
